project_id = "kuksfjgxpzyilwwwksdx"

[functions.auth-login]
verify_jwt = false

[functions.manage-booking]
verify_jwt = false

[functions.send-booking-notification]
verify_jwt = false

[functions.send-otp]
verify_jwt = false
